




.build/nano328/src/heatingcontrol.cpp : src/heatingcontrol.ino
	@mkdir -p .build/nano328/src
	@echo [93msrc/heatingcontrol.ino[0m
	@/usr/local/bin/ino preproc  -o $@ $^


all : .build/nano328/src/heatingcontrol.cpp
	@true

